name: Create Feature Branch -> Main Pull Request
on:
  push:
    branches:
      - feature/*
      - feat/*
      - chore/*
      - patch/*
      - fix/*
      - bug/*
      - task/*
      - story/*
      - claudio/*
      - mariano/*
      - lewis/*
      - daniel/*
      - COMP-*
      - cursor/*
      - codex/*
      - chas/*
      - tofik/*
jobs:
  create-pull-request:
    runs-on: warp-ubuntu-latest-arm64-4x
    continue-on-error: true
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Add permissions
        run: git config --global --add safe.directory /github/workspace
      - name: Check out epository code
        uses: actions/checkout@v3
      - name: Create pull request
        if: ${{ success() }}
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "main"
          pr_title: "[dev] [${{ github.actor }}] ${{ github.ref_name }}"
          pr_label: "automated-pr"
          pr_body: |
            This is an automated pull request to merge ${{ github.ref_name }} into dev.
            It was created by the [Auto Pull Request] action.
